language: python

python:
  - 3.6

bundler_args: --retry 3

install:
  - sudo apt-get update
  - ./utils/travis_miniconda.sh
  - PATH="$HOME/miniconda/bin:$PATH"
  - conda env create -f environment.yml
  - source activate project

script:
  - travis_wait python utils/travis_runner.py
